### ISSUE TITLE
I cant install dependencies

### ISSUE THREAD

**Issue by Neisvestney** [moriartydev/DKControl_Fork#1]
![image](https://user-images.githubusercontent.com/30620564/87142952-027bfe80-c2ae-11ea-89f5-773576fb6cd8.png)
![image](https://user-images.githubusercontent.com/30620564/87143021-1f183680-c2ae-11ea-8b9f-46614a738a04.png)

Мелик, ну как так-то?

**Comment by moriartydev** [comment]
Никита, ошибОчка в README, нужно писать просто "npm install"
